name: Github secrets to env
description: Expose github secrets and vars as shell variables
inputs:
  secrets:
    description: 'Expose secrets'
    required: false
    default: true
  vars:
    description: 'Expose variables'
    required: false
    default: true
runs:
  using: 'composite'
  steps:
    - name: Exposing github vars as shell variables
      if: ${{ env.vars }}
      shell: bash
      env:
        MYSECRET: ${{ toJson(env.vars) }}
      run: |
        EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
        echo "$MYVARS" | jq -r 'to_entries[] | \"\(.key)<<$EOF\n\(.value)\n$EOF\n\""' >> $GITHUB_ENV

    - name: Exposing github secrets as shell variables
      if: ${{ env.secrets }}
      shell: bash
      env:
        MYSECRET: ${{ toJson(env.secrets) }}
      run: |
        EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
        echo "$MYSECRET" | jq -r 'to_entries[] | \"\(.key)<<$EOF\n\(.value)\n$EOF\n\""' >> $GITHUB_ENV
      
