name: Github secrets to env
description: Expose github secrets and vars as shell variables
inputs:
  secrets_:
    description: 'Expose secrets'
    required: false
    default: false
  vars_:
    description: 'Expose variables'
    required: false
    default: true
runs:
  using: 'composite'
  steps:
    - name: Exposing github vars as shell variables
      if: ${{ inputs.vars_ == 'true' }}
      shell: bash
      env:
        MYVARS: ${{ toJson(vars) }}
      run: |
        EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
        echo "$MYVARS" | jq -r 'to_entries[] | \"\(.key)<<$EOF\n\(.value)\n$EOF\n\""' >> $GITHUB_ENV

    - name: Exposing github secrets as shell variables
      if: ${{ inputs.secrets_ == 'true' }}
      shell: bash
      env:
        MYSECRET: ${{ toJson(secrets) }}
      run: |
        EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
        echo "$MYSECRET" | jq -r 'to_entries[] | \"\(.key)<<$EOF\n\(.value)\n$EOF\n\""' >> $GITHUB_ENV
      
