on: [push]

jobs:
  test:
    runs-on: ubuntu-latest 
    name: A job to expose secrets and vars
    steps: 
      - uses: actions/checkout@v3
      - shell: bash
        env:
          MYSECRET: ${{ toJson(secrets) }}
        run: |
        EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
        echo "$MYSECRET" | jq -r 'to_entries[] | \"\(.key)<<$EOF\n\(.value)\n$EOF\n\""' >> $GITHUB_ENV
      - shell: bash
        run: echo $FOO